import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import { createApp } from '../src/app.js';
import { createPool, migrate } from '../src/db.js';
import { sanitizeAdvice, fallbackAdvice } from '../src/advice.js';
import { buildPlanWorkbook, launchSteps } from '../src/export.js';

const DB = process.env.TEST_DATABASE_URL || 'postgres://postgres@localhost:5433/postly_test';
const cfg = { trustProxyHops: 0, sessionDays: 1, adminEmails: [], adminApiKey: '', anthropicApiKey: 'KEY', anthropicModel: 'claude-sonnet-5-5',
  helpName: 'Hostbotics', helpUrl: 'https://hostbotics.net/', whatsapp: {}, whatsappEnabled: false, webhookEnabled: false };

let pool, server, url, script, calls;
before(async () => {
  pool = createPool(DB);
  await migrate(pool, { retries: 2, delayMs: 200 });
  await pool.query('truncate users cascade');
  const llm = async (_u, o) => { calls.push(JSON.parse(o.body)); return new Response(JSON.stringify(script.shift() ?? { content: [{ type: 'text', text: 'ok' }] }), { status: 200 }); };
  server = createApp(cfg, { pool, fetchImpl: llm, fetchPage: async () => '<html><body>x</body></html>' }).listen(0);
  url = `http://127.0.0.1:${server.address().port}`;
});
after(async () => { server.close(); await pool.end(); });

function client() {
  let cookie = '';
  const call = async (method, path, body) => {
    const res = await fetch(url + path, { method, headers: { 'content-type': 'application/json', ...(cookie && { cookie }) }, body: body === undefined ? undefined : JSON.stringify(body) });
    for (const c of res.headers.getSetCookie?.() ?? []) cookie = c.split(';')[0];
    const buf = Buffer.from(await res.arrayBuffer()); const text = buf.toString('utf8'); let json; try { json = JSON.parse(text); } catch {}
    return { status: res.status, json, text, buf, headers: res.headers };
  };
  return { get: (p) => call('GET', p), post: (p, b = {}) => call('POST', p, b), put: (p, b) => call('PUT', p, b) };
}
const signup = async (email) => { const c = client(); await c.post('/api/auth/register', { email, password: 'correct horse 1', businessName: 'Einvite' }); return c; };
const tool = (platform) => ({ stop_reason: 'tool_use', content: [{ type: 'tool_use', id: 'tu_1', name: 'create_campaign_draft', input: { platform } }] });
const txt = (t) => ({ stop_reason: 'end_turn', content: [{ type: 'text', text: t }] });

const ADVICE = [
  { platform: 'Instagram', fit: 'Best fit', why: 'Couples browse wedding ideas visually.', budget_share: 60, first_step: 'Reel of an invite being made' },
  { platform: 'Google', fit: 'Good fit', why: 'Searches for digital wedding invitations in Lebanon.', budget_share: 40, first_step: 'Keywords' },
  { platform: 'TikTok', fit: 'Later', why: 'Needs lots of video.', budget_share: 30, first_step: '' },
  { platform: 'Myspace', fit: 'Best fit', why: 'not a real option', budget_share: 100 },
  { platform: 'Facebook', fit: 'whatever', why: 'x'.repeat(999), budget_share: 500 },
];

test('advice is limited to known platforms, ranked, clamped; "Later" gets no budget', () => {
  const a = sanitizeAdvice(ADVICE);
  assert.deepEqual(a.map((x) => x.platform), ['Instagram', 'Google', 'Facebook', 'TikTok']);   // Myspace dropped, best first
  assert.equal(a.find((x) => x.platform === 'Facebook').budget_share, 100);
  assert.equal(a.find((x) => x.platform === 'Facebook').why.length, 260);
  assert.equal(a.find((x) => x.platform === 'TikTok').budget_share, 0);
  assert.deepEqual(sanitizeAdvice('nope'), []);
  assert.equal(sanitizeAdvice(fallbackAdvice({})).length, 5);
});

test('channel advice: generated by the model, stored, readable later, per user', async () => {
  const c = await signup('adv1@z.com');
  await c.put('/api/business', { description: 'Digital wedding invitations', country: 'Lebanon', budget: '$100 – $300' });
  assert.deepEqual((await c.get('/api/advice/channels')).json.advice, null);
  calls = []; script = [txt('Here: ' + JSON.stringify(ADVICE))];
  const r = await c.post('/api/advice/channels');
  assert.equal(r.status, 200);
  assert.equal(r.json.ai, true);
  assert.equal(r.json.advice[0].platform, 'Instagram');
  assert.match(calls[0].system, /ONLY these platforms/);
  assert.match(calls[0].messages[0].content, /Digital wedding invitations/);
  const saved = (await c.get('/api/advice/channels')).json;
  assert.equal(saved.advice.length, 4);
  assert.deepEqual((await (await signup('adv2@z.com')).get('/api/advice/channels')).json.advice, null);
  assert.equal((await client().post('/api/advice/channels')).status, 401);
  const me = (await c.get('/api/me')).json.business;
  assert.ok(!('channel_advice' in me));
});

test('without AI the advice is generic guidance, and junk model output falls back too', async () => {
  const c = await signup('adv3@z.com');
  calls = []; script = [txt('no idea')];
  const r = await c.post('/api/advice/channels');
  assert.equal(r.json.ai, false);
  assert.ok(r.json.advice.length >= 4);
});

test('the chat assistant is given the channel advice and told not to draft before a platform is chosen', async () => {
  const c = await signup('adv4@z.com');
  calls = []; script = [txt(JSON.stringify(ADVICE))];
  await c.post('/api/advice/channels');
  calls = []; script = [txt('Start with Instagram or Google. Which one?')];
  const r = await c.post('/api/chat', { message: 'I want to run ads, where should I start?' });
  assert.equal(r.json.campaign, null);                               // nothing drafted
  assert.match(calls[0].system, /Channel advice already given[\s\S]*Instagram: Best fit \(60% of budget\)/);
  assert.match(calls[0].system, /do not create a draft until a platform is chosen/);
  assert.match(calls[0].system, /Later" or "Skip for now"/);
});

test('Excel export: valid workbook, plan + steps sheets, formulas neutralised, owner only', async () => {
  const buf = await buildPlanWorkbook({
    campaign: { title: '=HYPERLINK("http://evil")', platform: 'Instagram', status: 'pending', budget_per_day: 20, duration_days: 7 },
    brief: { objective: '+cmd', audience: { age_min: 24, age_max: 38, genders: 'All', locations: ['Lebanon'], interests: ['Weddings'], notes: '' }, placements: ['Reels'],
      creative: { formats: ['Reel'], ideas: ['@idea'] }, copy: { headline: 'H', primary_text: 'T', cta: 'Learn more' }, landing: 'https://x.example', kpis: ['CPL'], assumptions: [], questions: [] },
    business: { name: 'Einvite', website: 'einvite.me' }, notes: ['No pixel'],
  });
  assert.equal(buf.subarray(0, 2).toString(), 'PK');           // xlsx is a zip
  const wb = new ExcelJS.Workbook(); await wb.xlsx.load(buf);
  assert.deepEqual(wb.worksheets.map((w) => w.name), ['Campaign plan', 'Steps to launch']);
  const rows = []; wb.getWorksheet('Campaign plan').eachRow((r) => rows.push([r.getCell(1).value, r.getCell(2).value]));
  assert.ok(rows.some(([k, v]) => k === 'Budget' && v === '$20 per day'));
  assert.ok(rows.some(([k, v]) => k === 'Total budget' && v === '$140'));
  for (const [, v] of rows) assert.ok(typeof v !== 'string' || !/^[=+\-@]/.test(v), `formula-like cell: ${v}`);
  assert.ok(wb.getWorksheet('Steps to launch').rowCount >= 6);
  assert.ok(launchSteps('Google')[0].includes('Google Ads'));

  const owner = await signup('xl1@z.com');
  script = [tool('Instagram'), txt('{}'), txt('Done')];
  const chat = await owner.post('/api/chat', { message: 'Create an Instagram campaign for me.' });
  const id = chat.json.campaign.id;
  const dl = await owner.get(`/api/campaigns/${id}/plan.xlsx`);
  assert.equal(dl.status, 200);
  assert.match(dl.headers.get('content-type'), /spreadsheetml/);
  assert.match(dl.headers.get('content-disposition'), /attachment; filename="[\w-]+-plan\.xlsx"/);
  assert.equal(dl.buf.subarray(0, 2).toString(), 'PK');
  assert.equal((await (await signup('xl2@z.com')).get(`/api/campaigns/${id}/plan.xlsx`)).status, 404);
  assert.equal((await client().get(`/api/campaigns/${id}/plan.xlsx`)).status, 401);
});
